# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1c\n\x07Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\"\n\x08Response\x12\x16\n\x0eis_auth_result\x18\x01 \x01(\x08\x32,\n\x0b\x41uthService\x12\x1d\n\x06IsAuth\x12\x08.Request\x1a\t.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=46
  _REQUEST._serialized_end=74
  _RESPONSE._serialized_start=76
  _RESPONSE._serialized_end=110
  _AUTHSERVICE._serialized_start=112
  _AUTHSERVICE._serialized_end=156
# @@protoc_insertion_point(module_scope)
